services:
  flowset-tasklist-react:
    container_name: "flowset-tasklist-react-community"
    image: flowset/flowset-tasklist-react-community:${FLOWSET_TASKLIST_VERSION}
    build:
      context: ..
      args:
        - VITE_APP_VERSION=${FLOWSET_TASKLIST_VERSION}
    ports:
      - "80:80"
    environment:
      - VITE_APP_LOCALE=${FLOWSET_TASKLIST_LOCALE}
      - VITE_BPM_ENGINE_API_URL=${BPM_ENGINE_API_URL}
      - VITE_BPM_ENGINE_TYPE=${BPM_ENGINE_TYPE}